# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      # Prefix all commit messages with "COMP: "
      prefix: "COMP"
