SET (CTEST_PROJECT_NAME "Slicer3")
SET (CTEST_NIGHTLY_START_TIME "23:00:00 EDT")
SET (CTEST_DROP_METHOD "xmlrpc")
SET (CTEST_DROP_SITE "http://www.na-mic.org/Dart")
SET (CTEST_DROP_LOCATION "Slicer3")
SET (CTEST_TRIGGER_SITE "")
SET (CTEST_COMPRESS_SUBMISSION ON)

