SET(CTEST_PROJECT_NAME "ITK")
SET(CTEST_NIGHTLY_START_TIME "21:00:00 EDT")
SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "public.kitware.com")
SET(CTEST_DROP_LOCATION "/cgi-bin/HTTPUploadDartFile.cgi")
SET(CTEST_TRIGGER_SITE "http://public.kitware.com/cgi-bin/Submit-Insight-TestingResults.cgi")
SET(DART_TESTING_TIMEOUT 15000)
