set(CTEST_PROJECT_NAME "ITK")
set(CTEST_NIGHTLY_START_TIME "21:00:00 EDT")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "public.kitware.com")
set(CTEST_DROP_LOCATION "/cgi-bin/HTTPUploadDartFile.cgi")
set(CTEST_TRIGGER_SITE "http://public.kitware.com/cgi-bin/Submit-Insight-TestingResults.cgi")
set(DART_TESTING_TIMEOUT 15000)
