/*=auto=========================================================================

  Portions (c) Copyright 2005 Brigham and Women's Hospital (BWH) All Rights Reserved.

  See Doc/copyright/copyright.txt
  or http://www.slicer.org/copyright/copyright.txt for details.

  Program:   3D Slicer
  Module:    $RCSfile: vtkSlicerVolumeMathGUI.h,v $
  Date:      $Date: 2006/03/19 17:12:29 $
  Version:   $Revision: 1.3 $

=========================================================================auto=*/
#ifndef __vtkSlicerVolumeMathGUI_h
#define __vtkSlicerVolumeMathGUI_h

#include "vtkSlicerBaseGUIWin32Header.h"
#include "vtkSlicerModuleGUI.h"

#include "vtkMRMLScene.h"
#include "vtkSlicerVolumeMathLogic.h"


class vtkSlicerSliceWidget;
class vtkKWFrame;
class vtkKWScaleWithEntry;
class vtkKWPushButton;
class vtkSlicerNodeSelectorWidget;
class vtkKWMultiColumnList;
class vtkKWLoadSaveButton;

class VTK_SLICERVOLUMEMATH_EXPORT vtkSlicerVolumeMathGUI : public vtkSlicerModuleGUI
{
  public:
  static vtkSlicerVolumeMathGUI *New();
  vtkTypeMacro(vtkSlicerVolumeMathGUI,vtkSlicerModuleGUI);
  void PrintSelf(ostream& os, vtkIndent indent);

   // Description: Get/Set MRML node
  vtkGetObjectMacro (Logic, vtkSlicerVolumeMathLogic);
  vtkSetObjectMacro (Logic, vtkSlicerVolumeMathLogic);
  
  // Description: Get/Set MRML node
  vtkGetObjectMacro (SlicerVolumeMathNode, vtkMRMLVolumeMathNode);

  // Description:
  // Create widgets
  virtual void BuildGUI ( );

  // Description:
  // Add obsereves to GUI widgets
  virtual void AddGUIObservers ( );
  
  // Description:
  // Remove obsereves to GUI widgets
  virtual void RemoveGUIObservers ( );
  
  // Description:
  // Process events generated by Logic
  virtual void ProcessLogicEvents ( vtkObject *caller, unsigned long event,
                                    void *callData );

  // Description:
  // Pprocess events generated by GUI widgets
  virtual void ProcessGUIEvents ( vtkObject *caller, unsigned long event,
                                  void *callData );

  // Description:
  // Pprocess events generated by MRML
  virtual void ProcessMRMLEvents ( vtkObject *caller, unsigned long event, 
                                  void *callData);
  // Description:
  // Describe behavior at module startup and exit.
  virtual void Enter ( ){};
  virtual void Exit ( ){};

protected:
  vtkSlicerVolumeMathGUI();
  virtual ~vtkSlicerVolumeMathGUI();
  vtkSlicerVolumeMathGUI(const vtkSlicerVolumeMathGUI&);
  void operator=(const vtkSlicerVolumeMathGUI&);

  // Description:
  // Updates GUI widgets based on parameters values in MRML node
  void UpdateGUI();

  // Description:
  // Updates parameters values in MRML node based on GUI widgets 
  void UpdateMRML();
  
  vtkSlicerNodeSelectorWidget* GrayscaleSelector;
  vtkSlicerNodeSelectorWidget* LabelmapSelector; 
  vtkKWPushButton* ApplyButton;
  
  vtkSlicerVolumeMathLogic *Logic;
  vtkMRMLVolumeMathNode* SlicerVolumeMathNode;
  //vtkKWText* VolStatsResult;
  vtkKWMultiColumnList* ResultList;
  vtkKWLoadSaveButton* SaveToFile;
  
};

#endif

