
package ifneeded SlicerBaseGUITcl 3.0 [list 
  source [file join $dir SliceViewerInteractor.tcl]
  source [file join $dir SWidget.tcl]
  source [file join $dir SliceSWidget.tcl]
  source [file join $dir SeedSWidget.tcl]
  source [file join $dir CsysSWidget.tcl]
  source [file join $dir FiducialsSWidget.tcl]
  source [file join $dir GridSWidget.tcl]
  source [file join $dir CrosshairSWidget.tcl]
  source [file join $dir RegionsSWidget.tcl]
  source [file join $dir SlicePlaneSWidget.tcl]
  source [file join $dir Slicer2Import.tcl]
  source [file join $dir Loader.tcl]
  source [file join $dir LoadVolume.tcl]
  source [file join $dir LoadTransform.tcl]
  source [file join $dir FilteredDirectoryDialog.tcl]
  source [file join $dir XcedeCatalogImport.tcl]
  source [file join $dir XcatalogImport.tcl]
  source [file join $dir XnatXcatImport.tcl]
  source [file join $dir XnatPublishScene.tcl]         
  source [file join $dir MRMLWatcher.tcl]
]
