FIND_PATH(XERCESC_INCLUDE_DIR xercesc/dom/DOM.hpp /usr/include /usr/local/include)

FIND_LIBRARY(XERCESC_LIBRARY NAMES xercesc PATH /usr/lib /usr/local/lib) 

IF (XERCESC_INCLUDE_DIR)
   SET(XERCESC_FOUND TRUE)
   MESSAGE(STATUS "Found XercesC: ${XERCESC_INCLUDE_DIR}")
ENDIF (XERCESC_INCLUDE_DIR)


IF (XERCESC_FOUND)
   IF (NOT XERCESC_FIND_QUIETLY)
      MESSAGE(STATUS "Found XercesC: ${XERCESC_LIBRARY}")
   ENDIF (NOT XERCESC_FIND_QUIETLY)
ELSE (XERCESC_FOUND)
   IF (XERCESC_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find XercesC-lib")
   ENDIF (XERCESC_FIND_REQUIRED)
ENDIF (XERCESC_FOUND)
