FIND_PATH(WFENGINE_INCLUDE_DIR WFEMain.h /usr/include /usr/local/include)

FIND_LIBRARY(WFENGINE_LIBRARY NAMES WFDirectInterface PATH /usr/lib /usr/local/lib) 

IF (WFENGINE_INCLUDE_DIR)
   SET(WFENGINE_FOUND TRUE)
   SET(WFENGINE_INCLUDE_DIR ${WFENGINE_INCLUDE_DIR} ${WFENGINE_INCLUDE_DIR}/engine
                            ${WFENGINE_INCLUDE_DIR}/interfaces ${WFENGINE_INCLUDE_DIR}/interfaces/direct 
                            ${WFENGINE_INCLUDE_DIR}/xmlManager)
ENDIF (WFENGINE_INCLUDE_DIR)


IF (WFENGINE_FOUND)
   IF (NOT WFENGINE_FIND_QUIETLY)
      MESSAGE(STATUS "Found WFENGINE: ${WFENGINE_INCLUDE_DIR}")
   ENDIF (NOT WFENGINE_FIND_QUIETLY)
ELSE (WFENGINE_FOUND)
   IF (WFENGINE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find WFEngine")
   ENDIF (WFENGINE_FIND_REQUIRED)
ENDIF (WFENGINE_FOUND)
