#ifndef __vtkSlicerComponentGUI_h
#define __vtkSlicerComponentGUI_h

#include "vtkObject.h"
#include "vtkKWObject.h"

class vtkSlicerApplicationGUI;
class vtkSlicerLogic;
class vtkSlicerApplicationLogic;
class vtkKWWindowBase;
class vtkKWApplication;
class vtkSlicerGUIUpdate;
class vtkSlicerLogicUpdate;


// Description:
// This is a base class that all SlicerGUIs get derived from.
// A GUI can access its Slicer look & feel through its
// "App" data member. 
//
class vtkSlicerComponentGUI : public vtkKWObject
{

 public:
    static vtkSlicerComponentGUI* New ( );
    vtkTypeRevisionMacro ( vtkSlicerComponentGUI, vtkKWObject );

    // GUI FUNCTIONS:
    virtual int BuildGUI ( vtkSlicerApplicationGUI *app ) { return 1; }
    virtual void SetWindow ( vtkKWWindowBase *win );
    vtkKWWindowBase *GetWindow ( );
    virtual void SetSlicerApplication ( vtkSlicerApplicationGUI *app );
    vtkSlicerApplicationGUI *GetSlicerApplication ( );
    virtual void SetKWApplication ( vtkKWApplication *app ) ;
    vtkKWApplication *GetKWApplication ( );

    // MEDIATOR FUNCTiONS:
    virtual void SetLogic ( vtkSlicerApplicationLogic *logic );
    vtkSlicerApplicationLogic *GetLogic ( );
    // Description:
    // Create observers on widgets defined in this class using the following paradigm:
    // this->AddCallbackCommandObserver ( ObservedWidget, vtkCommand::SomeEvent);
    virtual void AddGUIObservers ( ) { }
    // Description:
    // Create observers on logic in application layer using the vtk paradigm:
    // Logic->mylogic->AddObserver ( vtkCommand::ModifiedEvent, this->LogicCommand);
    virtual void AddLogicObservers ( ) { }
    // propagate events generated by kwwidgets to application layer
    virtual void ProcessCallbackCommandEvents ( vtkObject *caller,
                                                unsigned long event,
                                                void *callData );
    // propagate events generated in application layer to GUI
    virtual void UpdateGUIWithLogicEvents ( vtkObject *caller, unsigned long event,
                                void *callData );
    // alternative method to propagate events generated in GUI to app layer
    virtual void UpdateLogicWithGUIEvents ( vtkObject *caller, unsigned long event,
                                    void *callData );
    
    
 protected:
    // pointer to the window in which the GUI is displayed.
    vtkKWWindowBase *KWWindow;
    // pointer to the vtkSlicerApplicationGUI to which GUI belongs.
    vtkSlicerApplicationGUI *SlicerApplication;
    // pointer to the vtkKWApplication to which GUI belongs.
    vtkKWApplication *KWApplication;
    
    // GUI's interface to the application layer;
    vtkSlicerApplicationLogic *Logic;
    vtkSlicerGUIUpdate *LogicCommand;
    // alternative Logic interface to the GUI layer.
    vtkSlicerLogicUpdate *GUICommand;
    
    // constructor, destructor.
    vtkSlicerComponentGUI ( );
    ~vtkSlicerComponentGUI ( );
    
 private:
    vtkSlicerComponentGUI ( const vtkSlicerComponentGUI& ); // Not implemented.
    void operator = ( const vtkSlicerComponentGUI& ); // Not implemented.
};


#endif


