#-----------------------------------------------------------------------------
# Sanity checks
set(expected_defined_vars CMAKE_CTEST_COMMAND GIT_EXECUTABLE Subversion_SVN_EXECUTABLE EXTENSION_NAME EXTENSION_SOURCE_DIR EXTENSION_SUPERBUILD_BINARY_DIR EXTENSION_BUILD_SUBDIRECTORY EXTENSION_ENABLED Slicer_CMAKE_DIR Slicer_EXTENSIONS_CMAKE_DIR Slicer_DIR EXTENSION_COMPILER EXTENSION_BITNESS Slicer_EXTENSION_CMAKE_GENERATOR Slicer_WC_REVISION QT_VERSION_MAJOR QT_VERSION_MINOR)
foreach(var ${expected_defined_vars})
  if(NOT DEFINED ${var})
    message(FATAL_ERROR "Variable ${var} is not defined !")
  endif()
endforeach()

set(expected_existing_vars CMAKE_CTEST_COMMAND GIT_EXECUTABLE Subversion_SVN_EXECUTABLE Slicer_CMAKE_DIR Slicer_EXTENSIONS_CMAKE_DIR Slicer_DIR)
foreach(var ${expected_existing_vars})
  if(NOT EXISTS "${${var}}")
    message(FATAL_ERROR "Variable ${var} is set to an inexistent directory or file ! [${${var}}]")
  endif()
endforeach()

#-----------------------------------------------------------------------------
# The following variable can be used while testing the script
#-----------------------------------------------------------------------------
set(CTEST_EXTRA_VERBOSE TRUE)
if(NOT DEFINED RUN_CTEST_CONFIGURE)
  set(RUN_CTEST_CONFIGURE TRUE)
endif()
set(RUN_CTEST_BUILD TRUE)
set(RUN_CTEST_TEST TRUE)
set(RUN_CTEST_PACKAGES TRUE)
set(RUN_CTEST_SUBMIT TRUE)

#-----------------------------------------------------------------------------
# Prepare external project configuration arguments
set(EXTENSION_SCRIPT ${Slicer_EXTENSIONS_CMAKE_DIR}/SlicerBlockBuildPackageAndUploadExtension.cmake)
set(EXTENSION_COMMAND_ARG_LIST
"set(CTEST_CMAKE_GENERATOR \"${Slicer_EXTENSION_CMAKE_GENERATOR}\")
set(GIT_EXECUTABLE \"${GIT_EXECUTABLE}\")
set(Subversion_SVN_EXECUTABLE \"${Subversion_SVN_EXECUTABLE}\")
set(CMAKE_MAKE_PROGRAM \"${CMAKE_MAKE_PROGRAM}\")
set(CMAKE_C_COMPILER \"${CMAKE_C_COMPILER}\")
set(CMAKE_CXX_COMPILER \"${CMAKE_CXX_COMPILER}\")
set(BUILD_TESTING \"${BUILD_TESTING}\")
set(RUN_CTEST_SUBMIT \"${RUN_CTEST_SUBMIT}\")
set(EXTENSION_BUILD_OPTIONS_STRING \"${EXTENSION_BITNESS}bits-Qt${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}\")
set(EXTENSION_COMPILER \"${EXTENSION_COMPILER}\")
set(EXTENSION_NAME \"${EXTENSION_NAME}\")
set(EXTENSION_CATEGORY \"${EXTENSION_CATEGORY}\")
set(EXTENSION_STATUS \"${EXTENSION_STATUS}\")
set(EXTENSION_ICONURL \"${EXTENSION_ICONURL}\")
set(EXTENSION_CONTRIBUTORS \"${EXTENSION_CONTRIBUTORS}\")
set(EXTENSION_DESCRIPTION \"${EXTENSION_DESCRIPTION}\")
set(EXTENSION_HOMEPAGE \"${EXTENSION_HOMEPAGE}\")
set(EXTENSION_SCREENSHOTURLS \"${EXTENSION_SCREENSHOTURLS}\")
set(EXTENSION_SOURCE_DIR \"${EXTENSION_SOURCE_DIR}\")
set(EXTENSION_SUPERBUILD_BINARY_DIR \"${EXTENSION_SUPERBUILD_BINARY_DIR}\")
set(EXTENSION_BUILD_SUBDIRECTORY \"${EXTENSION_BUILD_SUBDIRECTORY}\")
set(EXTENSION_ENABLED \"${EXTENSION_ENABLED}\")
set(EXTENSION_DEPENDS \"${EXTENSION_DEPENDS}\")
set(Slicer_CMAKE_DIR \"${Slicer_CMAKE_DIR}\")
set(Slicer_DIR \"${Slicer_DIR}\")
set(Slicer_EXTENSIONS_TRACK_QUALIFIER \"${Slicer_EXTENSIONS_TRACK_QUALIFIER}\")
set(Slicer_WC_REVISION \"${Slicer_WC_REVISION}\")
set(MIDAS_PACKAGE_URL \"${MIDAS_PACKAGE_URL}\")
set(MIDAS_PACKAGE_EMAIL \"${MIDAS_PACKAGE_EMAIL}\")
set(MIDAS_PACKAGE_API_KEY \"${MIDAS_PACKAGE_API_KEY}\")")
foreach(dep ${EXTENSION_DEPENDS})
  set(EXTENSION_COMMAND_ARG_LIST "${EXTENSION_COMMAND_ARG_LIST}
set(${dep}_DIR \"${${dep}_DIR}\")")
endforeach()

#-----------------------------------------------------------------------------
set(CTEST_EXTRA_VERBOSE_ARG "")
if(CTEST_EXTRA_VERBOSE)
  set(CTEST_EXTRA_VERBOSE_ARG "V")
endif()

#-----------------------------------------------------------------------------
# Set CTEST_BUILD_CONFIGURATION here
# See http://www.cmake.org/cmake/help/cmake-2-8-docs.html#variable:CMAKE_CFG_INTDIR
if(CMAKE_CONFIGURATION_TYPES)
  set(CTEST_BUILD_CONFIGURATION ${CMAKE_CFG_INTDIR})
else()
  set(CTEST_BUILD_CONFIGURATION ${CMAKE_BUILD_TYPE})
endif()
set(EXTENSION_COMMAND_BUILD_CONF_ARG_LIST
  -C ${CTEST_BUILD_CONFIGURATION}
  -DCTEST_BUILD_CONFIGURATION:STRING=${CTEST_BUILD_CONFIGURATION}
  )

#-----------------------------------------------------------------------------
# Set EXTENSION_TEST_COMMAND
set(EXTENSION_TEST_COMMAND_ARG_LIST "${EXTENSION_COMMAND_ARG_LIST}
set(RUN_CTEST_CONFIGURE \"${RUN_CTEST_CONFIGURE}\")
set(RUN_CTEST_BUILD \"${RUN_CTEST_BUILD}\")
set(RUN_CTEST_TEST \"${RUN_CTEST_TEST}\")
set(RUN_CTEST_PACKAGES \"${RUN_CTEST_PACKAGES}\")
set(RUN_CTEST_UPLOAD \"FALSE\")")

set(script_args_file ${CMAKE_CURRENT_BINARY_DIR}/${EXTENSION_NAME}-test-command-args.cmake)
file(WRITE ${script_args_file} ${EXTENSION_TEST_COMMAND_ARG_LIST})

set(EXTENSION_TEST_COMMAND ${CMAKE_CTEST_COMMAND} ${EXTENSION_COMMAND_BUILD_CONF_ARG_LIST} -DCTEST_MODEL:STRING=${CTEST_MODEL} -DSCRIPT_ARGS_FILE:FILEPATH=${script_args_file} -S ${EXTENSION_SCRIPT} -V${CTEST_EXTRA_VERBOSE_ARG})

#-----------------------------------------------------------------------------
# Set EXTENSION_UPLOAD_COMMAND
set(EXTENSION_UPLOAD_COMMAND_ARG_LIST "${EXTENSION_COMMAND_ARG_LIST}
set(RUN_CTEST_CONFIGURE \"${RUN_CTEST_CONFIGURE}\")
set(RUN_CTEST_BUILD \"${RUN_CTEST_BUILD}\")
set(RUN_CTEST_TEST \"${RUN_CTEST_TEST}\")
set(RUN_CTEST_PACKAGES \"${RUN_CTEST_PACKAGES}\")
set(RUN_CTEST_UPLOAD \"TRUE\")
set(EXTENSION_ARCHITECTURE \"${EXTENSION_ARCHITECTURE}\")
set(EXTENSION_BITNESS \"${EXTENSION_BITNESS}\")
set(EXTENSION_OPERATING_SYSTEM \"${EXTENSION_OPERATING_SYSTEM}\")")

set(script_args_file ${CMAKE_CURRENT_BINARY_DIR}/${EXTENSION_NAME}-upload-command-args.cmake)
file(WRITE ${script_args_file} ${EXTENSION_UPLOAD_COMMAND_ARG_LIST})

set(EXTENSION_UPLOAD_COMMAND ${CMAKE_CTEST_COMMAND} ${EXTENSION_COMMAND_BUILD_CONF_ARG_LIST} -DCTEST_MODEL:STRING=${CTEST_MODEL} -DSCRIPT_ARGS_FILE:FILEPATH=${script_args_file} -S ${EXTENSION_SCRIPT} -V${CTEST_EXTRA_VERBOSE_ARG})
