#
# Slicer3 specific CMake requirements
#

  CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
  IF(COMMAND CMAKE_POLICY)
    CMAKE_POLICY(SET CMP0003 NEW)
  ENDIF(COMMAND CMAKE_POLICY)
  MARK_AS_ADVANCED(CMAKE_BACKWARDS_COMPATIBILITY)
