cmake_minimum_required(VERSION 3.28.0...3.28.0 FATAL_ERROR)

set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/..")
set(PROJECT_NAME Slicer)
set(Slicer_BINARY_INNER_SUBDIR Slicer-build)
set(CMAKE_CURRENT_SOURCE_DIR "C:/src")
set(CMAKE_GENERATOR "Ninja")

string(REPEAT "b" 10 _outer_suffix)
set(_outer_binary_dir "C:/${_outer_suffix}")
set(_inner_binary_dir "${_outer_binary_dir}/Slicer-build")

if(TEST_CASE STREQUAL "outer_too_long")
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_BINARY_DIR "${_outer_binary_dir}x")
elseif(TEST_CASE STREQUAL "reported_path")
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_BINARY_DIR "C:/S-itk-main/Slicer/build")
elseif(TEST_CASE STREQUAL "multi_config_reported_path")
  set(CMAKE_GENERATOR "Ninja Multi-Config")
  set(CMAKE_CONFIGURATION_TYPES Debug)
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_BINARY_DIR "C:/S-itk-main/Slicer/build")
elseif(TEST_CASE MATCHES "^multi_config_")
  set(CMAKE_GENERATOR "Ninja Multi-Config")
  set(Slicer_SUPERBUILD ON)
  if(TEST_CASE STREQUAL "multi_config_default" OR TEST_CASE STREQUAL "multi_config_default_inner"
      OR TEST_CASE STREQUAL "multi_config_default_skipped")
    set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo")
    set(CMAKE_CURRENT_BINARY_DIR "C:/")
    if(TEST_CASE STREQUAL "multi_config_default_inner")
      set(Slicer_SUPERBUILD OFF)
      set(CMAKE_CURRENT_BINARY_DIR "C:/Slicer-build")
    elseif(TEST_CASE STREQUAL "multi_config_default_skipped")
      set(Slicer_SKIP_ROOT_DIR_MAX_LENGTH_CHECK ON)
    endif()
  elseif(TEST_CASE STREQUAL "multi_config_inner_boundary" OR TEST_CASE STREQUAL "multi_config_inner_over_boundary")
    set(CMAKE_CONFIGURATION_TYPES Debug)
    set(Slicer_SUPERBUILD OFF)
    set(CMAKE_CURRENT_BINARY_DIR "C:/bbbb/Slicer-build")
    if(TEST_CASE STREQUAL "multi_config_inner_over_boundary")
      set(CMAKE_CURRENT_BINARY_DIR "C:/bbbbb/Slicer-build")
    endif()
  elseif(TEST_CASE STREQUAL "multi_config_longest_boundary" OR TEST_CASE STREQUAL "multi_config_longest_over_boundary")
    set(CMAKE_CONFIGURATION_TYPES "Debug;Release")
    set(CMAKE_CURRENT_BINARY_DIR "C:/bb")
    if(TEST_CASE STREQUAL "multi_config_longest_over_boundary")
      string(APPEND CMAKE_CURRENT_BINARY_DIR "b")
    endif()
  else()
    set(CMAKE_CONFIGURATION_TYPES Debug)
    set(CMAKE_CURRENT_BINARY_DIR "C:/bbbb")
    if(TEST_CASE STREQUAL "multi_config_over_boundary")
      string(APPEND CMAKE_CURRENT_BINARY_DIR "b")
    endif()
  endif()
elseif(TEST_CASE STREQUAL "inner_too_long" OR TEST_CASE STREQUAL "inner_skipped")
  set(Slicer_SUPERBUILD OFF)
  set(CMAKE_CURRENT_BINARY_DIR "${_inner_binary_dir}x")
  if(TEST_CASE STREQUAL "inner_skipped")
    set(Slicer_SKIP_ROOT_DIR_MAX_LENGTH_CHECK ON)
  endif()
elseif(TEST_CASE STREQUAL "long_source")
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_SOURCE_DIR "C:/source/tree/longer/than/build")
  set(CMAKE_CURRENT_BINARY_DIR "${_outer_binary_dir}")
elseif(TEST_CASE STREQUAL "other_generator")
  set(CMAKE_GENERATOR "Visual Studio 17 2022")
  string(REPEAT "b" 37 _legacy_suffix)
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_BINARY_DIR "C:/${_legacy_suffix}")
else()
  set(Slicer_SUPERBUILD ON)
  set(CMAKE_CURRENT_BINARY_DIR "${_outer_binary_dir}")
endif()

include(SlicerCheckRootDirLength)

if(TEST_CASE STREQUAL "other_generator")
  set(_expected_build_limit 40)
elseif(TEST_CASE STREQUAL "multi_config_default_skipped")
  set(_expected_build_limit -2)
elseif(TEST_CASE STREQUAL "multi_config_longest_boundary" OR TEST_CASE STREQUAL "multi_config_longest_over_boundary")
  set(_expected_build_limit 5)
elseif(TEST_CASE STREQUAL "multi_config_boundary" OR TEST_CASE STREQUAL "multi_config_over_boundary")
  set(_expected_build_limit 7)
elseif(TEST_CASE STREQUAL "multi_config_inner_boundary" OR TEST_CASE STREQUAL "multi_config_inner_over_boundary")
  set(_expected_build_limit 20)
elseif(TEST_CASE STREQUAL "multi_config_reported_path")
  set(_expected_build_limit 7)
elseif(Slicer_SUPERBUILD)
  set(_expected_build_limit 13)
else()
  set(_expected_build_limit 26)
endif()
if(NOT Slicer_BUILD_DIR_MAX_LENGTH EQUAL _expected_build_limit)
  message(FATAL_ERROR "Unexpected build limit: ${Slicer_BUILD_DIR_MAX_LENGTH}")
endif()
if(Slicer_SUPERBUILD)
  set(_expected_source_limit 40)
else()
  set(_expected_source_limit 53)
endif()
if(NOT Slicer_ROOT_DIR_MAX_LENGTH EQUAL _expected_source_limit)
  message(FATAL_ERROR "Unexpected source limit: ${Slicer_ROOT_DIR_MAX_LENGTH}")
endif()

if(TEST_CASE)
  return()
endif()

set(Slicer_SUPERBUILD OFF)
set(CMAKE_CURRENT_BINARY_DIR "${_inner_binary_dir}")
include(SlicerCheckRootDirLength)
if(NOT Slicer_BUILD_DIR_MAX_LENGTH EQUAL 26)
  message(FATAL_ERROR "Unexpected inner build limit: ${Slicer_BUILD_DIR_MAX_LENGTH}")
endif()

foreach(_case IN ITEMS
    outer_too_long reported_path inner_too_long inner_skipped long_source other_generator
    multi_config_reported_path multi_config_boundary multi_config_over_boundary
    multi_config_longest_boundary multi_config_longest_over_boundary
    multi_config_inner_boundary multi_config_inner_over_boundary
    multi_config_default multi_config_default_inner multi_config_default_skipped)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" "-DTEST_CASE=${_case}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE _result
    ERROR_VARIABLE _error
    )
  if(_case STREQUAL "inner_skipped" OR _case STREQUAL "long_source" OR _case STREQUAL "other_generator"
      OR _case STREQUAL "multi_config_boundary" OR _case STREQUAL "multi_config_longest_boundary"
      OR _case STREQUAL "multi_config_inner_boundary" OR _case STREQUAL "multi_config_default_skipped")
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "${_case} failed: ${_error}")
    endif()
  elseif(_case STREQUAL "multi_config_default" OR _case STREQUAL "multi_config_default_inner")
    if(_result EQUAL 0 OR NOT _error MATCHES "leaves no usable Windows")
      message(FATAL_ERROR "${_case} was not rejected as expected: ${_error}")
    endif()
  elseif(_result EQUAL 0 OR NOT _error MATCHES "binary directory has too many characters")
    message(FATAL_ERROR "${_case} was not rejected as expected: ${_error}")
  endif()
endforeach()

message("SUCCESS")
