FIND_PACKAGE(LoadableModule REQUIRED)
IF(LoadableModule_FOUND)
   INCLUDE(${LoadableModule_USE_FILE})
ENDIF(LoadableModule_FOUND)

UTILITY_SOURCE(GENERATELM_EXE GenerateLM ./ GenerateLM.cxx)
IF (NOT GENERATELM_EXE)
  FIND_PROGRAM(GENERATELM_EXE GenerateLM PATHS ${GenerateLM_BINARY_DIR} DOC "GenerateLM executable")
  MESSAGE(ERROR " Requires GenerateLM executable. Please specify its location.")
ENDIF (NOT GENERATELM_EXE)

# create the .lm files
# usage: GENERATE_LM(foo_SRCS XML_FILE)
MACRO(GENERATELM SOURCES)
    # what is the filename without the extension
    GET_FILENAME_COMPONENT(TMP_FILENAME ${ARGV1} NAME_WE)
        
    # the input file might be full path so handle that
    GET_FILENAME_COMPONENT(TMP_FILEPATH ${ARGV1} PATH)

    # compute the input filename
    IF (TMP_FILEPATH)
      SET(TMP_INPUT ${TMP_FILEPATH}/${TMP_FILENAME}.txt) 
    ELSE (TMP_FILEPATH)
      SET(TMP_INPUT ${CMAKE_CURRENT_SOURCE_DIR}/${TMP_FILENAME}.txt)
    ENDIF (TMP_FILEPATH)

    # add custom command to output
    ADD_CUSTOM_COMMAND(
      OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h
      DEPENDS ${GENERATELM_EXE} ${TMP_INPUT}
      COMMAND ${GENERATELM_EXE}
        ${TMP_INPUT} ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.cxx
    )

    # add custom command to output
    ADD_CUSTOM_COMMAND(
      OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.cxx
      DEPENDS ${GENERATELM_EXE} ${TMP_INPUT}
      COMMAND ${GENERATELM_EXE}
        ${TMP_INPUT} ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.cxx
    )

    # mark the Lib.cxx file as a source file

    # mark the Lib.h file as a header file
    SET_SOURCE_FILES_PROPERTIES(${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h PROPERTIES HEADER_FILE_ONLY TRUE)
    SET_SOURCE_FILES_PROPERTIES(${TMP_FILENAME}Lib.cxx PROPERTIES OBJECT_DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h)

    SET(${SOURCES} ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.h ${${SOURCES}}) 
    SET(${SOURCES} ${CMAKE_CURRENT_BINARY_DIR}/${TMP_FILENAME}Lib.cxx ${${SOURCES}}) 
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
ENDMACRO(GENERATELM)
