#!/bin/sh
echo 'Your work tree has not been configured for Slicer development.
Paste the following commands into a shell:

  ./Utilities/SetupForDevelopment.sh

See
https://www.slicer.org/w/index.php/Documentation/Nightly/Developers/DevelopmentWithGit
 for more information.'
exit 1
