"""Generate a lazily-loading drop-in replacement for the ``vtk`` module.

The ``vtk.py`` shim distributed with VTK eagerly star-imports more than a
hundred binary modules, which costs close to a second at every application
startup even though a typical session touches only a fraction of them.

This script, run at build time, imports every VTK module once, records which
module provides each public attribute, and writes a replacement ``vtk``
module that resolves attributes on demand (PEP 562 module __getattr__):
``vtk.vtkPolyData`` imports only ``vtkmodules.vtkCommonDataModel``.
The generated file is placed on the Python path ahead of the eager shim.

Compatibility notes, mirroring the eager shim:
- ``__path__`` is aliased to the ``vtkmodules`` package so that submodule
  imports such as ``import vtk.util.numpy_support`` keep working.
- The ``vtkmodules.util`` convenience re-exports (``calldata_type``,
  ``vtkImageScalarTypeNameMacro``, the ``vtkVariant`` helpers) stay eager.
- ``from vtk import *`` resolves every attribute and therefore imports
  everything, matching the eager behavior at the eager cost.

Usage: GenerateLazyVtkModule.py --output /path/to/vtk.py
"""

import argparse
import importlib
import os
import re
import sys


def module_order():
    """Return the vtkmodules submodule names in the order used by
    vtkmodules.all, so that attribute collisions resolve to the same module
    as with eager star-imports (the last import wins).
    """
    import vtkmodules.all
    source = open(vtkmodules.all.__file__).read()
    return re.findall(r"^from \.(\w+) import \*", source, re.MULTILINE)


def build_index(names):
    index = {}
    failed = []
    for name in names:
        try:
            module = importlib.import_module("vtkmodules." + name)
        except ImportError:
            failed.append(name)
            continue
        for attribute in dir(module):
            if not attribute.startswith("_"):
                index[attribute] = name
    return index, failed


TEMPLATE = '''"""Lazily-loading vtk module (generated by GenerateLazyVtkModule.py).

Provides the same namespace as the eager ``vtk`` module distributed with
VTK, but each attribute access imports only the vtkmodules submodule that
provides it. Import ``vtkmodules.all`` to force everything to load.
"""

import importlib as _importlib

import vtkmodules as _vtkmodules

# Make this module look like the vtkmodules package so that submodule
# imports such as ``import vtk.util.numpy_support`` keep working.
__path__ = _vtkmodules.__path__
__version__ = _vtkmodules.__version__

# Convenience re-exports, kept eager to match the eager shim.
from vtkmodules.util.vtkConstants import vtkImageScalarTypeNameMacro
from vtkmodules.util.misc import calldata_type
from vtkmodules.util.vtkVariant import *

_ATTRIBUTE_MODULE = {index}


def __getattr__(name):
    module_name = _ATTRIBUTE_MODULE.get(name)
    if module_name is None:
        raise AttributeError("module 'vtk' has no attribute %r" % (name,))
    module = _importlib.import_module("vtkmodules." + module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(list(globals()) + list(_ATTRIBUTE_MODULE)))
'''


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True)
    arguments = parser.parse_args(argv)

    names = module_order()
    if not names:
        print("error: could not determine vtkmodules import order", file=sys.stderr)
        return 1
    index, failed = build_index(names)
    if failed:
        print("note: skipped unimportable modules: %s" % ", ".join(failed))

    entries = ",\n    ".join(f'"{attribute}": "{index[attribute]}"'
                             for attribute in sorted(index))
    # On a fresh build this rule may run before anything else has created
    # the destination directory.
    os.makedirs(os.path.dirname(os.path.abspath(arguments.output)), exist_ok=True)
    with open(arguments.output, "w") as stream:
        stream.write(TEMPLATE.replace("{index}", "{\n    %s,\n}" % entries))
    print("generated %s: %d attributes from %d modules"
          % (arguments.output, len(index), len(names)))
    return 0


if __name__ == "__main__":
    status = main(sys.argv[1:])
    sys.stdout.flush()
    sys.stderr.flush()
    # Exit without interpreter teardown: unloading a hundred freshly built
    # VTK modules can crash in static destructors in the bare build
    # environment, and the generated file is already written and closed.
    os._exit(status)
